on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build_linux32:
    runs-on: self-hosted
    defaults:
      run:
        shell: sh
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Build 32-bit
        working-directory: ${{ github.workspace }}
        run: |
          premake5 gmake2 --tag_version="${{ github.ref_name }}"
          cd projects/apakr_32/linux/gmake2
          make config=releasewithsymbols_x86 CXX=g++-10 CXXFLAGS="-std=c++17 LDFLAGS="-lpthread -lcurl"
      - name: Release
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_name: A5R13L/gmsv_apakr_plugin
          repo_token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
          body: "gmsv_apakr_plugin"
          file: projects/apakr_32/linux/gmake2/x86/ReleaseWithSymbols/gmsv_apakr_32_linux.dll
          asset_name: gmsv_apakr_plugin_32.so